[package]
name = "kirby-speedscore-recorders"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[workspace]
members = [
    "client",
    "server"
]

[dependencies]
